sudo: required
services:
  - docker

before_install:
  - docker build -t iamnoman07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iamnoman07/react-test npm test

after_success:
  - docker build -t iamnoman07/multi-client ./client
  - docker build -t iamnoman07/multi-nginx ./nginx
  - docker build -t iamnoman07/multi-server ./server
  - docker build -t iamnoman07/multi-worker ./worker

## Now we need to put these images in docker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push iamnoman07/multi-client
  - docker push iamnoman07/multi-nginx
  - docker push iamnoman07/multi-server
  - docker push iamnoman07/multi-worker
