sudo: required
services:
  - docker

before_install:
  - docker build -t iamnoman07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iamnoman07/react-test npm test

after_success:
  - docker build -t iamnoman07/multi-client ./client
  - docker build -t iamnoman07/multi-nginx ./nginx
  - docker build -t iamnoman07/multi-server ./server
  - docker build -t iamnoman07/multi-worker ./worker

## Now we need to put these images in docker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push iamnoman07/multi-client
  - docker push iamnoman07/multi-nginx
  - docker push iamnoman07/multi-server
  - docker push iamnoman07/multi-worker

deploy:
  # this is where we say what is our provider
  provider: elasticbeanstalk
  # put the region, that was used while creating your EBS instance
  region: "us-east-2"
  # here you put the name of the instance you created, your app name basically
  app: "docker-with-react"
  # put the envoirnment name
  env: "DockerWithReact-env"
  #Travis will zip all your code and put it in zip and store it inside s3
  # it will then tell aws that you can redoply your app with this file
  # put the s3 bucket name which is compatible to your EBS instance
  bucket_name: "elasticbeanstalk-us-east-2-584507583045"
  # now you gonna use the folder in that bucket_name
  bucker_path: "docker-with-react"
  # here i am just telling if something changed in master, only then you
  # should deploy it
  on:
    branch: master
# now we are providing both access and secure key
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"