version: '3'

services:
  # Docker compose will start a service of postgres using its latest image
  postgres:
    image: 'postgres:latest'

  # we are going to use redis latest image
  redis:
    image: 'redis:latest'
# creating a server service
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    # providing a Dockerfile for image
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      # providing
    depends_on:
    - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
        - /app/node_modules
        - ./worker:/app
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
